application: absolute-vertex-595
version: 1
runtime: php
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /documents
  static_dir: documents
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /sitemap.xml
  static_dir: js
- url: /(.+\.php)
  script: \1
- url: (.*?)/(.+\.php)
  script: \2/\1  # specify a script
- url: /video
  static_dir: video
- url: /
  script: index.html

